name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Recommended LTS version
          cache: 'npm'        # Caches node_modules for faster runs

      - name: Install dependencies
        run: |
          cd server
          npm ci --prefer-offline  # Uses package-lock.json for reproducible builds

      - name: Run tests
        run: |
          cd server
          npm test

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST \
            "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json"